# Generated by Django 2.2.1 on 2020-11-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_blog_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tagline',
            field=models.TextField(max_length=5000),
        ),
    ]
