# Generated by Django 2.2.1 on 2020-11-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201118_1903'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='biaoji',
        ),
        migrations.RenameModel(
            old_name='Article',
            new_name='wenzhang',
        ),
        migrations.RenameModel(
            old_name='Author',
            new_name='zuozhe',
        ),
    ]
