# Generated by Django 2.2.1 on 2020-11-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201118_1913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='biaoji',
            new_name='biaojia',
        ),
        migrations.RenameModel(
            old_name='wenzhang',
            new_name='wenzhanga',
        ),
        migrations.RenameModel(
            old_name='zuozhe',
            new_name='zuozhea',
        ),
    ]
