# Generated by Django 2.2.1 on 2020-11-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article_author_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者', 'verbose_name_plural': '作者'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
    ]
