# Generated by Django 2.2.1 on 2020-11-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201119_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标记', 'verbose_name_plural': '标记'},
        ),
    ]
