# Generated by Django 2.2.1 on 2020-11-28 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_host_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='cpsy',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='磁盘剩余'),
            preserve_default=False,
        ),
    ]
