# Generated by Django 2.2.1 on 2020-11-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_host_cpsy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, verbose_name='hostname')),
            ],
            options={
                'verbose_name': '监控主机ip',
                'verbose_name_plural': '监控主机ip',
            },
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': '监控日志', 'verbose_name_plural': '监控日志'},
        ),
    ]
