# Generated by Django 2.2.1 on 2020-11-29 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20201129_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Hostname', verbose_name='主机'),
        ),
    ]
