# Generated by Django 2.2.1 on 2020-11-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20201129_1105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hostname',
            new_name='Hostnamea',
        ),
    ]
