# Generated by Django 2.2.1 on 2020-11-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20201130_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': '图片', 'verbose_name_plural': '图片'},
        ),
        migrations.RenameField(
            model_name='images',
            old_name='img',
            new_name='image',
        ),
    ]
