# Generated by Django 2.2.1 on 2020-12-01 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20201130_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='图片标识'),
            preserve_default=False,
        ),
    ]
