# Generated by Django 2.2.1 on 2020-12-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(max_length=50, verbose_name='图片标识(唯一)'),
        ),
    ]
